[package]
name = "blockchain"
version = "0.1.0"
authors = ["Simon Strassl <stuff@sigmoid.at>"]

[dependencies]
log = "0.3.8"
env_logger = "0.4.3"
rust-crypto = "0.2.35"
byteorder = "1.0.0"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0"